events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:8080;
    }

    upstream order_service {
        server order-service:8081;
    }

    upstream delivery_service {
        server delivery-service:8082;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders/ {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /deliveries/ {
            proxy_pass http://delivery_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
